apiVersion: v1
kind: Service
metadata:
  name: events-web-svc
  labels:
    app: events-web-svc
spec:
  selector:
    app: events-web
    ver: v1.0
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer